// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwgdkbulehhtrjjoglkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3Z2RrYnVsZWhodHJqam9nbGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzc4MjQsImV4cCI6MjA3MTg1MzgyNH0.VdsvEqbWwOmkfRhau2u6S5wVwgK9V1dV1wVrl6s34wY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});